# Uncomment and fill in the platforms you use to enable the "Sponsor" button.
# Docs: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [your-username]
# ko_fi: your-username
# open_collective: your-collective
# patreon: your-username
# custom: ["https://example.com/donate"]
