"""jarvis_protocol — Python bindings for the JarvisVR wire protocol (v1).

The JSON Schemas in ``shared-protocol/schema`` are the source of truth; this
package provides pydantic models plus :func:`encode`, :func:`decode`,
:func:`new_message`, and :func:`validate` built on top of them.

Quick start::

    from jarvis_protocol import new_message, encode, decode, validate, MessageType, AgentSpeech

    msg = new_message(MessageType.AGENT_SPEECH, AgentSpeech(text="Hi", final=True), session="S")
    wire = encode(msg)            # compact JSON text frame
    validate(wire)                # raises ProtocolValidationError if non-conformant
    env = decode(wire)            # -> Envelope
"""

from __future__ import annotations

from .catalog import KNOWN_TYPES, TYPE_TO_SCHEMA, MessageType
from .codec import (
    MessageLike,
    ProtocolValidationError,
    decode,
    encode,
    is_valid,
    iter_errors,
    new_id,
    new_message,
    now_ms,
    parse_payload,
    to_dict,
    validate,
)
from .models import (
    Ack,
    AgentInfo,
    AgentObservation,
    AgentSpeech,
    AgentThinking,
    Anchor,
    Annotation,
    Arrangement,
    AudioEvent,
    AudioScene,
    Camera,
    Capabilities,
    ClientBargeIn,
    ClientBye,
    ClientHello,
    ClientInteraction,
    ClientScene,
    ClientSettingsGet,
    ClientSettingsUpdate,
    CurrentLlm,
    Envelope,
    Gaze,
    GazeSource,
    Hand,
    Heartbeat,
    HoloDestroy,
    HoloLayout,
    HoloObject,
    HoloUpdate,
    Interaction,
    Intrinsics,
    LlmSettings,
    LlmSettingsUpdate,
    OrchestrationAgent,
    OrchestrationAgentStatus,
    OrchestrationHandoff,
    OrchestrationPlan,
    AuthoringAgent,
    AuthoringSkill,
    ClientAgentInspect,
    ClientAuthorAgent,
    ClientAuthorList,
    ClientAuthorSkill,
    ClientTraceGet,
    ClientTraceSubscribe,
    MemoryInfo,
    MemoryRecentItem,
    ServerAgentInfo,
    ServerAuthoring,
    ServerTrace,
    SkillInfo,
    TraceAgent,
    TraceEvent,
    PAYLOAD_MODELS,
    PerceptionAction,
    PerceptionRequest,
    PerceptionState,
    PerceptionStream,
    Pose,
    ProtocolError,
    ProviderCapabilities,
    ProviderEntry,
    SceneAnchor,
    SceneObject,
    SceneObjects,
    ServerHelloAck,
    ServerSettings,
    SoundLabel,
    Speaker,
    StreamState,
    Surface,
    TextInput,
    Thermal,
    ThinkingStage,
    Transform,
    VisionFormat,
    VisionFrame,
    VisionStreamState,
    VisionTransport,
    VoiceInfo,
)
from .schemas import SCHEMA_DIR, load_schemas
from .version import PROTOCOL_VERSION, SUPPORTED_VERSIONS

__version__ = PROTOCOL_VERSION

__all__ = [
    "PROTOCOL_VERSION",
    "SUPPORTED_VERSIONS",
    "__version__",
    # catalog
    "MessageType",
    "TYPE_TO_SCHEMA",
    "KNOWN_TYPES",
    # codec
    "MessageLike",
    "ProtocolValidationError",
    "new_message",
    "encode",
    "decode",
    "validate",
    "is_valid",
    "iter_errors",
    "to_dict",
    "parse_payload",
    "now_ms",
    "new_id",
    # schemas
    "SCHEMA_DIR",
    "load_schemas",
    # models
    "Envelope",
    "PAYLOAD_MODELS",
    "Capabilities",
    "ClientHello",
    "AgentInfo",
    "VoiceInfo",
    "ServerHelloAck",
    "TextInput",
    "AgentThinking",
    "AgentSpeech",
    "Transform",
    "HoloObject",
    "HoloUpdate",
    "HoloDestroy",
    "HoloLayout",
    "ClientInteraction",
    "Pose",
    "Surface",
    "SceneAnchor",
    "ClientScene",
    "ProtocolError",
    "ClientBye",
    "ClientBargeIn",
    "Heartbeat",
    "Ack",
    # v1.1 perception models
    "Intrinsics",
    "VisionFrame",
    "AudioEvent",
    "SoundLabel",
    "AudioScene",
    "Gaze",
    "SceneObject",
    "SceneObjects",
    "VisionStreamState",
    "StreamState",
    "PerceptionState",
    "PerceptionRequest",
    "Annotation",
    "AgentObservation",
    # v1.1 settings (§5.15)
    "ClientSettingsGet",
    "LlmSettingsUpdate",
    "ClientSettingsUpdate",
    "ProviderCapabilities",
    "ProviderEntry",
    "CurrentLlm",
    "LlmSettings",
    "ServerSettings",
    # v1.2 orchestration (§9)
    "OrchestrationAgent",
    "OrchestrationPlan",
    "OrchestrationAgentStatus",
    "OrchestrationHandoff",
    # v1.3 tracing + authoring (§10)
    "ClientTraceSubscribe",
    "ClientTraceGet",
    "ClientAgentInspect",
    "ClientAuthorList",
    "ClientAuthorSkill",
    "ClientAuthorAgent",
    "TraceEvent",
    "TraceAgent",
    "ServerTrace",
    "SkillInfo",
    "MemoryRecentItem",
    "MemoryInfo",
    "ServerAgentInfo",
    "AuthoringAgent",
    "AuthoringSkill",
    "ServerAuthoring",
    # enums
    "Anchor",
    "Interaction",
    "ThinkingStage",
    "Arrangement",
    "Hand",
    # v1.1 perception enums
    "Camera",
    "VisionFormat",
    "VisionTransport",
    "PerceptionStream",
    "PerceptionAction",
    "GazeSource",
    "Speaker",
    "Thermal",
]
